input {
  mongodb {
    uri => "mongodb://root:rootpassword@192.168.101.1:27017/dgaid_db"
    placeholder_db_dir => "/usr/share/logstash/mongodb/"
    placeholder_db_name => "logstash_sqlite.db"
    collection => "transactions"
    batch_size => 5000
  }

  mongodb {
    uri => "mongodb://root:rootpassword@192.168.101.1:27017/dgaid_db"
    placeholder_db_dir => "/usr/share/logstash/mongodb/"
    placeholder_db_name => "logstash_sqlite2.db"
    collection => "transactions_api"
    batch_size => 5000
  }

  mongodb {
    uri => "mongodb://root:rootpassword@192.168.101.1:27017/dgaid_db"
    placeholder_db_dir => "/usr/share/logstash/mongodb/"
    placeholder_db_name => "logstash_sqlite3.db"
    collection => "transaction_third_party"
    batch_size => 5000
  }
}

filter {
  mutate {
    remove_field => ["_id"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "dgaid_%{[@metadata][collection]}"
  }

  stdout { codec => json }
}
