version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    volumes:
      - ./dga_mongodb/dga_mongodb/dgaid_db:/opt/data
    command: >
      bash -c "
      chmod 600 /opt/data/keyfile &&
      chown mongodb:mongodb /opt/data/keyfile &&
      mongod --replSet rs0 --bind_ip_all --auth --keyFile /opt/data/keyfile
      "